name: EMHASS
description: Energy Management for Home Assistant
url: https://github.com/davidusb-geek/emhass
version: 0.0.17
slug: emhass
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
ports:
  5000/tcp: 5000
homeassistant_api: true
options:
  log_level: info
  seconds_to_publish_data: 30
  optimization_task_at: "21:35"
  action: "dayahead-optim"
  costfun: "profit"
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  seconds_to_publish_data: int(1,120)
  optimization_task_at: str
  action: list(dayahead-optim|perfect-optim)
  costfun: list(profit|cost|self-consumption)

